######################## default configuration ####################
baseURL = "https://techbudget.it/"
title = "TechBudget"
theme = "twentytwenty"
# lingua cambiata da languageName = "En" languageCode = "en-us" in IT per reinderizzamento sui motori
# di ricerca ma non se cambi qualcosa o rompa il sito
languageName = "It"
languageCode = "it-IT"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "techbudget-it" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here
# google analytics
googleAnalytics = "G-386RCSHK02" # example : UA-123-45



############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"

############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "/"
weight = 1

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 2

[[menu.main]]
name = "About"
URL = "about"
weight = 3

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 4


[[menu.main]]
name = "♥"
URL = "supporter"
weight = 5

# only desktop menu
[[menu.desktop]]
name = "Contact"
URL = "contact"
weight = 1


#################### default parameters ################################
[params]
# Meta data
description = "TechBudget.it | Stanco dei costosissimi consigli tecnologici, ho deciso di aiutare chi cerca il miglior prodotto al minor prezzo."
author = "Delmo"

# cookies
[params.cookies]
enable = true
expire_days = 2

# banner
[params.banner]
heading = "Il Metodo Giusto Per Approcciarsi Alla Tecnologia"
image = "https://res.cloudinary.com/techbudget-it/image/upload/v1623102322/welcome.jpg"

# blog
[params.blog]
heading = "Basta pagare prodotti sovrapprezzati."

# call to action
[params.call_to_action]
enable = true
title = "Rimani in contatto con me"
content = "*Vuoi essere aggiornato sul dietro le quinte del progetto? <br>Vuoi conoscere qualcosa in più di me?*"
button_label = "Seguimi sul Canale Telegram"
button_url = "https://t.me/TechBudget_it"

# gallery
[params.gallery]
enable = false

[[params.gallery.gallery_item ]]
image = "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80"

[[params.gallery.gallery_item ]]
image = "images/2020-square-1.png"


# footer
[params.footer]
title = "About Me"
content = "Appassionato di informatica da sempre. <br>Ora sento il bisogno di condividere quello che ho imparato (a mie spese) in questi anni consigliandovi i migliori prodotti per qualità/prezzo."
address = "Latina, Italia"
hours = "Ogni Mercoledì alle 15 un nuovo appuntamento. <br>Stay tuned."
copyright = "Copyright &copy; 2021 a hugo theme by [themefisher](https://themefisher.com) <br> Icon by [Prettycons](https://www.flaticon.com/authors/prettycons)"

############################# social site ########################
[params.social]
# yelp = "#"
# facebook = "#"
# twitter = "#"
instagram = "https://instagram.com/techbudget.it"
email = "techbudget@techie.com"
# linkedin = "#"
