######################## default configuration ####################
baseURL = "https://techbudget.it/"
title = "TechBudget"
theme = "twentytwenty"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name NON SO SE FUNZIONA SOLO COSì
disqusShortname = "techbudget-it" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here
# google analytics
googleAnalytics = "G-386RCSHK02" # example : UA-123-45



############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"

############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "/"
weight = 1

[[menu.main]]
name = "About"
URL = "about"
weight = 2

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 4

#Le pagine inserite per il supporto non funzionano ancora
#[[menu.main]]
#name = "Support"
#URL = "support"
#weight = 5

# only desktop menu
[[menu.desktop]]
name = "Contact"
URL = "contact"
weight = 1


#################### default parameters ################################
[params]
# Meta data
description = "Stanco dei costosissimi consigli tecnologici, ho deciso di aiutare chi cerca il miglior prodotto al minor prezzo."
author = "Themefisher"

# cookies
[params.cookies]
enable = true
expire_days = 2

# banner
[params.banner]
heading = "Il Metodo Giusto Per Approcciarsi Alla Tecnologia"
image = "https://res.cloudinary.com/techbudget-it/image/upload/v1623102322/welcome.jpg"

# blog
[params.blog]
heading = "Basta pagare prodotti sovrapprezzati."

# call to action
[params.call_to_action]
enable = false
title = "Contact us for more information."
content = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
button_label = "Contact Us"
button_url = "contact"

# gallery
[params.gallery]
enable = false

[[params.gallery.gallery_item ]]
image = "images/2020-square-2.png"

[[params.gallery.gallery_item ]]
image = "images/2020-square-1.png"


# footer
[params.footer]
title = "About This Site"
content = "Appassionato di informatica da sempre. <br>Ora sento il bisogno di condividere quello che ho imparato (a mie spese) in questi anni."
address = "Roma, Italia"
hours = "Ogni Mercoledì alle 15 un nuovo appuntamento. <br>Stay tuned."
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com) <br> Icon by [Prettycons](https://www.flaticon.com/authors/prettycons)"

############################# social site ########################
[params.social]
# yelp = "#"
# facebook = "#"
# twitter = "#"
instagram = "instagram.com/techbudget.it"
email = "techbudget@techie.com"
# linkedin = "#"
